language:
  node_js
node_js:
  - "12.16.2"
install:
  - npm install
before_script:
  - npm run build
  - npm start &
script:
  - nyc mocha ./index.js --exit
  - nyc report --reporter=text-lcov > coverage.lcov && codecov --inspect=0.0.0.0:3000 -t 5cbe7896-534a-42e8-bb5e-c9af9726fe57