language:
  node_js
node_js:
  - "12.16.2"
install:
  - "npm install"
before_script:
  - "npm run build"
  - "npm start &"
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
  - "npm test"